###
POST http://localhost:8080/api/socks/
Content-Type: application/json

{
  "sock": {
    "colour": "black",
    "size": "36.0",
    "cotton": 90
  },
  "quantity": 10
}

###
PUT http://localhost:8080/api/socks/
Content-Type: application/json

{
  "sock": {
    "colour": "black",
    "size": "36.0",
    "cotton": 80
  },
  "quantity": 5
}

###
GET http://localhost:8080/api/socks?colour=black&size=36.0&cottonMin80

###
GET http://localhost:8080/api/socks?colour=black&size=36.0&cottonMax100

###
DELETE http://localhost:8080/api/socks/
Content-Type: application/json

{
  "sock": {
    "colour": "black",
    "size": "36.0",
    "cotton": 80
  },
  "quantity": 5
}
